### ISSUE TITLE
Sound does not play

### ISSUE THREAD

**Issue by meemsbror** [SSundstrom/DWIMS#60]
Testing both safari om macos and chrome on android sound does not play when choosing song

**Comment by SSundstrom** [comment]
![image](https://user-images.githubusercontent.com/14053376/55709126-e244fc00-59e7-11e9-951d-5896e0542c8a.png)

Yeah, the problem is that the [spotify web player](https://developer.spotify.com/documentation/web-playback-sdk/) is still in beta and does not work on those platforms. 

To get around this to have a native Spotify app running and switch to that source in the settings.

![image](https://user-images.githubusercontent.com/14053376/55709253-351eb380-59e8-11e9-87d6-55a0f5f9c533.png)
